Switch color icons to imageHtml
bpmn-io/bpmn-js-color-picker pull request #29
Opened 2023-10-27 12:51 UTC by tk

Switching from imageUrl to imageHtml for the color icons.

This is necessary to show them in the vs-code-bpmn-io extension, that has a stricter ContentSecurityPolicy for inlined image sources and styles.

2023-10-27 12:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/bpmn-js-color-picker?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/bpmn-js-color-picker?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/bpmn-js-color-picker?pullRequest=29) it.</sub>

2023-10-30 08:14 UTC, smbea requested changes
The color icons cut off a little bit, see:
![Screenshot 2023-10-30 at 09 11 59](https://github.com/bpmn-io/bpmn-js-color-picker/assets/25825387/42fcd4b5-0677-4f51-98b1-d00a4cd04f47)

2023-10-31 13:10 UTC, smbea commented on colors/ColorPopupProvider.js
>      </svg>
Why the change of width from `22` to `20`? It causes the icons to be a bit smaller:

<img width="291" alt="Screenshot 2023-10-31 at 14 05 19" src="https://github.com/bpmn-io/bpmn-js-color-picker/assets/25825387/4096dc78-aef2-42ae-b111-45844f8da5e0">

I tested with `22` and it seems to work as expected.

2023-10-31 17:16 UTC, tk commented on colors/ColorPopupProvider.js
>      </svg>
The parent element constraints the icon to 1em (which is less than 20px on some high resolution monitors), which leads to the cut off effect mentioned in the first review when the browser shows the website with 100%. If you zoom in the cut off effect is gone.
I can change it back to 22, but then the cut off effect will be there again.

2023-11-02 09:06 UTC, tk commented
@smbea : I experimented and found a setting that hopefully solves both issues.

2023-11-02 10:58 UTC, smbea approved these changes
I think it looks good on the latest changes.
Thanks for your contribution!

2023-11-02 10:58 UTC, merged

2023-11-02 11:08 UTC, smbea commented
I will follow up with releasing this